
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from "prisma/config";
import { config as loadEnv } from "dotenv";
import { resolve } from "path";

// Load .env file from backend directory
loadEnv({ path: resolve(__dirname, ".env") });

// Get DATABASE_URL from environment - prefer DIRECT_URL for CLI operations (db push, migrations)
// DIRECT_URL should be the direct connection (without -pooler) from Neon dashboard
// For Neon: Use DIRECT_URL for CLI operations (db push, migrations), DATABASE_URL for app connections
const databaseUrl = process.env.DIRECT_URL || process.env.DATABASE_URL;

// Only require database URL if it's actually needed (not for prisma generate)
// prisma generate doesn't need database connection, so we allow it to be optional
const prismaConfig: any = {
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
};

// Only set datasource if database URL is available
// This allows prisma generate to work without database URL
if (databaseUrl) {
  prismaConfig.datasource = {
    url: databaseUrl,
  };
} else {
  // Warn but don't fail - prisma generate can work without it
  console.warn("⚠️  Neither DIRECT_URL nor DATABASE_URL found in environment variables");
  console.warn("⚠️  This is OK for 'prisma generate', but required for 'db push' and 'migrate'");
}

export default defineConfig(prismaConfig);
